export const speakers = [
  {
    name: "Lélio Renard Lavaud",
    company: "Mistral",
    company_website: "https://mistral.ai/",
    title: "VP of Engineering",
    linkedin: "https://www.linkedin.com/in/leliorenardlavaud/",
    profile_picture: "https://media.licdn.com/dms/image/v2/D4D03AQHAV33HaIjtMg/profile-displayphoto-shrink_800_800/B4DZOeKia.HoAc-/0/1733525383318?e=1761177600&v=beta&t=DBPgCrL9mubLFmttRVU4TKwhfZguhmrYCa6gSMZyeRs",
  },
  {
    name: "Andreas Blattmann",
    company: "Black Forest Labs",
    company_website: "https://bfl.ai",
    title: "Co-Founder",
    linkedin: "https://www.linkedin.com/in/andreas-blattmann-479038186/",
    profile_picture: "https://sessionize.com/image/1825-400o400o1-DVZNa6kD7Hfe14T2EnZxZ5.jpg",
  },
  {
    name: "Emil Eifrem",
    company: "Neo4j",
    company_website: "https://neo4j.com/",
    title: "Co-Founder & CEO",
    linkedin: "https://linkedin.com/in/emileifrem",
    profile_picture: "https://sessionize.com/image/9650-400o400o1-Jjsa7t42m8Ab6sNAUJox34.jpg",
  },
  {
    name: "Neil Zeghidour",
    company: "Kyutai",
    company_website: "https://kyutai.org/",
    title: "Co-Founder",
    linkedin: "https://www.linkedin.com/in/neil-zeghidour-a838aaa7/",
    profile_picture: "https://sessionize.com/image/3e7c-0o0o0-7BijR1w4EYJCkhBj1mEuBC.jpg",
  },
  {
    name: "Prateek Rungta",
    company: "OpenAI",
    company_website: "https://openai.com/",
    title: "Member Technical Staff",
    linkedin: "https://linkedin.com/in/rungtaprateek",
    profile_picture: "https://sessionize.com/image/b42e-400o400o1-Uu23Y4jydHnRuzvS3faACE.jpg",
  },
  {
    name: "Aparna Dhinakaran",
    company: "Arize AI",
    company_website: "https://arize.com/",
    title: "Co-Founder & Chief Product Officer",
    linkedin: "https://www.linkedin.com/in/aparnadhinakaran/",
    profile_picture: "https://sessionize.com/image/23ae-400o400o1-UfWFrGZUdkuEuH5k1PHzoE.jpg",
  },
  {
    name: "Paige Bailey",
    company: "DeepMind",
    company_website: "https://www.deepmind.com",
    title: "Technical Lead",
    linkedin: "https://www.linkedin.com/in/dynamicwebpaige/",
    profile_picture:
      "https://media.licdn.com/dms/image/v2/C5603AQFoBRGAnhVFuQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1516310626986?e=1758758400&v=beta&t=tvXDBMdcN6shvd48skRXJZkNUZJYKv8NJJOtCjgoYxg",
  },
  {
    name: "Yann Leger",
    company: "Koyeb",
    company_website: "https://www.koyeb.com/",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/yannleger/",
    profile_picture:
      "https://sessionize.com/image/398e-200o200o2-TmGow4cNSGRc5P3LzYETi3.jpg",
  },
  {
    name: "Laurent Sifre",
    company: "H Company",
    company_website: "https://www.hcompany.ai/",
    title: "Founder and CTO",
    linkedin: "https://www.linkedin.com/in/sifre/",
    profile_picture:
      "https://sessionize.com/image/57ee-0o0o0-3MQc7JQZMdGzZ9YMzVYUhE.jpg",
  },
  {
    name: "Steeve Morin",
    company: "ZML",
    company_website: "https://zml.ai/",
    title: "Founder",
    linkedin: "https://www.linkedin.com/in/steevemorin/",
    profile_picture:
      "https://sessionize.com/image/5fdc-0o0o0-Uiju8yumUmbKkmDMeCDNYB.jpg",
  },
  {
    name: "Robert Brennan",
    company: "OpenHands",
    company_website: "https://www.all-hands.dev",
    title: "CEO of All Hands AI & Co-Creator of OpenHands",
    linkedin: "https://linkedin.com/in/robert-a-brennan",
    profile_picture: "https://sessionize.com/image/62d2-400o400o1-3DaPYZY7SULucDrMfzQzkX.png",
  },
    {
    name: "Daniel Homola",
    company: "BMW Group",
    title: "AI Project Lead",
    linkedin: "https://linkedin.com/in/danielhomola",
    profile_picture: "https://sessionize.com/image/adcf-400o400o1-SRnJoDmtAVm1iHtrZ3Fbw5.jpg",
  },
  {
    name: "Vaibhav Srivastav",
    company: "Hugging Face",
    company_website: "https://huggingface.co/",
    title: "Head of Developer Experience and Community",
    linkedin: "https://www.linkedin.com/in/vaibhavs10/",
    profile_picture: "https://sessionize.com/image/b976-0o0o0-GdYSubDJnET7W9rxkaeEPB.jpg",
  },
  {
    name: "Ivan Burazin",
    company: "Daytona",
    company_website: "https://daytona.io",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/ivanburazin/",
    profile_picture: "https://sessionize.com/image/ba67-400o400o1-RZgw2DqaC7TEEp4b41MiwA.jpg",
  },
  {
    name: "Martin Woodward",
    company: "GitHub",
    company_website: "https://www.github.com",
    title: "Vice President of DevRel",
    linkedin: "https://www.linkedin.com/in/martinwoodward/",
    profile_picture: "https://sessionize.com/image/0b9b-400o400o1-3zvJTMdx1idyBM93y9QUxF.png",
  },
  {
    name: "Oleg	Šelajev",
    company: "Docker",
    company_website: "https://docker.com",
    title: "Testcontainers, AI, & Developer Relations",
    linkedin: "https://www.linkedin.com/in/shelajev/",
    profile_picture: "https://sessionize.com/image/5ca7-400o400o1-nLuHACqrBji1V81wQdQsWE.jpg",
  },
  {
    name: "Tuana Çelik",
    company: "LlamaIndex",
    company_website: "https://www.llamaindex.ai/",
    title: "DevRel & AI Engineer",
    linkedin: "https://www.linkedin.com/in/tuanacelik/",
    profile_picture: "https://sessionize.com/image/4adc-400o400o1-hrr259SGBYg7GmdDcmrWjv.jpg",
  },
  {
    name: "Peter Schuurman",
    company: "Google",
    company_website: "https://www.google.com",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/pwschuurman/",
    profile_picture: "https://sessionize.com/image/7932-400o400o1-WQi9TDxn2njDXoeiGxMsgY.jpg",
  },
  {
    name: "Ekin	Karabulut",
    company: "Nvidia",
    company_website: "https://www.nvidia.com",
    title: "AI/ML Developer Advocate",
    linkedin: "https://www.linkedin.com/in/ekin-karabulut-40baa2187/tr/?originalSubdomain=de",
    profile_picture: "https://sessionize.com/image/eecf-400o400o1-pZJa7toVkK4Y3yXanEAECR.jpg",
  },
  {
    name: "Alberto Castelo",
    company: "Shopify",
    company_website: "https://www.shopify.com",
    title: "Staff Machine Learning Engineer",
    linkedin: "https://www.linkedin.com/in/alberto-castelo-becerra/",
    profile_picture: "https://sessionize.com/image/e013-400o400o1-wBYZYt6bVB8bsfBHg4DeWE.jpg",
  },
  {
    name: "Aleksandar Mitic",
    company: "Shopify",
    company_website: "https://www.shopify.com",
    title: "Senior Software Engineer",
    profile_picture: "https://sessionize.com/image/5301-400o400o1-W58JTCwpdooqdCRgv5XpE2.png",
  },
  {
    name: "Jo Kelly-Fenton",
    company: "Spotify",
    company_website: "https://www.spotify.com",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/jo-kelly-fenton-68251ab4/",
    profile_picture: "https://sessionize.com/image/fc32-400o400o1-Umgjof5mCKrSaWsMNpTuz5.png",
  },
  {
    name: "Marlene Mhangami",
    company: "Microsoft",
    company_website: "https://www.microsoft.com",
    title: "Senior Developer Advocate",
    linkedin: "https://www.linkedin.com/in/marlenemhangami/",
    profile_picture: "https://sessionize.com/image/06f1-400o400o1-NuD8zgwsAzMT2MYadvSCe8.jpg",
  },
  {
    name: "Yves Brissaud",
    company: "Dagger",
    company_website: "https://dagger.io/",
    title: "Senior Software Engineer",
    linkedin: "linkedin.com/in/yvesbrissaud",
    profile_picture: "https://sessionize.com/image/f210-0o0o0-YXTvuA19HuKjFSRMSa2jcu.jpg",
  },
  {
    name: "Jesús Espino",
    company: "Gitpod",
    company_website: "https://www.gitpod.io",
    title: "Principal Engineer",
    linkedin: "https://www.linkedin.com/in/jesus-espino/",
    profile_picture: "https://sessionize.com/image/4415-400o400o1-axX3XUeP9guNAQug9iBjgf.jpg",
  },
  {
    name: "Thomas Schmidt",
    company: "Metabase",
    company_website: "https://www.metabase.com",
    title: "AI Engineer",
    linkedin: "https://www.linkedin.com/in/thomas-heinz-schmidt/",
    profile_picture: "https://sessionize.com/image/3ba7-400o400o1-Wd4mFZV9U1ojfdZCLPUEeD.png",
  },
  {
    name: "Miguel Betegon",
    company: "Sentry",
    title: "Member of Technical Staff",
    linkedin: "https://linkedin.com/in/miguel-betegon/",
    profile_picture: "https://sessionize.com/image/900d-0o0o0-TNK8JNPiQ8Kyyi7i7yBZLW.png",
  },
  {
    name: "Merrill Lutsky",
    company: "Graphite",
    company_website: "https://www.graphite.dev/",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/tomasreimers/",
    profile_picture: "https://sessionize.com/image/d663-0o0o0-LY7bkeWPfbVUVixhyjAZ16.jpg",
  },
  {
    name: "Lars Trieloff",
    company: "Adobe",
    company_website: "https://www.adobe.com",
    title: "Principal",
    linkedin: "https://www.linkedin.com/in/trieloff/?originalSubdomain=de",
    profile_picture: "https://sessionize.com/image/746b-400o400o1-X3k8wYiwiv5f6ytiM4KcZM.png",
  },
  {
    name: "Bertrand	Charpentier",
    company: "Pruna AI",
    company_website: "https://www.pruna.ai/",
    title: "Co-Founder, President, Chief Scientist",
    linkedin: "https://www.linkedin.com/in/bertrand-charpentier-76995ab6/",
    profile_picture: "https://sessionize.com/image/6506-400o400o1-LvxzBU9S96q8xpUogD4WnG.jpg",
  },
  {
    name: "Pierre Burgy",
    company: "Strapi",
    company_website: "https://www.strapi.io",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/pierre-burgy-strapi-88671673/",
    profile_picture: "https://sessionize.com/image/69a6-400o400o1-R8YmCmMn14oKvKC58rNqPn.jpg",
  },
  {
    name: "Rémi Louf",
    company: ".txt",
    company_website: "https://dottxt.ai/",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/remilouf/",
    profile_picture: "https://sessionize.com/image/db2c-0o0o0-wAQ77zd2BqLk8cksvtVsna.jpg",
  },  
  {
    name: "Robin Nabel",
    company: "Poolside",
    company_website: "https://poolside.ai",
    title: "Member of Technical Staff, Agent Model Lead",
    linkedin: "https://www.linkedin.com/in/robinnabel/",
    profile_picture: "https://sessionize.com/image/295f-0o0o0-TQhaShvnnQzxSfYfn9atPm.jpg",
  },
  {
    name: "Julien Launay",
    company: "Adaptive ML",
    company_website: "https://www.adaptive-ml.com/",
    title: "Co-founder and CEO",
    linkedin: "https://www.linkedin.com/in/julienlaunay/",
    profile_picture: "https://sessionize.com/image/bb16-0o0o0-R7yFhJkEhtXwREN1qA3gW5.png",
  },
  {
    name: "Raouf Chebri",
    company: "Tigris Data",
    company_website: "https://www.ai.engineer",
    title: "Developer Experience Engineer",
    linkedin: "https://www.linkedin.com/in/raoufchebri/",
    profile_picture: "https://media.licdn.com/dms/image/v2/D4E03AQGGcJvKMuYO2g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1726743088505?e=1761177600&v=beta&t=ogUO3rotyZJZ2A1XtDPbdUffIo5wORvr95CHR_37f4A",
  },
  {
    name: "Ben Dunphy",
    company: "AI Engineer",
    company_website: "https://www.ai.engineer",
    title: "Co-Founder",
    linkedin: "https://www.linkedin.com/in/benjamindunphy/",
    profile_picture: "https://www.ai.engineer/wf25speakers/ben_dunphy.jpeg",
  },
  {
    name: "Shawn Wang",
    company: "AI Engineer",
    company_website: "https://www.ai.engineer",
    title: "Co-Founder",
    linkedin: "https://www.linkedin.com/in/shawnswyxwang/",
    profile_picture: "https://user-images.githubusercontent.com/6764957/103350806-26d9ca80-4adc-11eb-9e53-a8ce9ca3f21f.jpeg",
  }
];
