export const speakers = [
  {
    name: "Andreas Blattmann",
    company: "Black Forest Labs",
    company_website: "https://bfl.ai",
    title: "Co-Founder",
    linkedin: "https://www.linkedin.com/in/andreas-blattmann-479038186/",
    profile_picture: "https://sessionize.com/image/1825-400o400o1-DVZNa6kD7Hfe14T2EnZxZ5.jpg",
  },
  {
    name: "Eiso Kant",
    company: "Poolside",
    company_website: "https://poolside.ai/",
    title: "Co-Founder & CTO",
    linkedin: "https://www.linkedin.com/in/eisokant/",
    profile_picture:
      "https://media.licdn.com/dms/image/v2/D5603AQHG92SlqT2ZAQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1728056785015?e=1758153600&v=beta&t=IrVgQHdcpJK8_LvIhVR3UAFWzN8mpIRYS9w9wZhQRHY",
  },
  {
    name: "Emil Eifrem",
    company: "Neo4j",
    company_website: "https://neo4j.com/",
    title: "Co-Founder & CEO",
    linkedin: "https://linkedin.com/in/emileifrem",
    profile_picture: "https://sessionize.com/image/9650-400o400o1-Jjsa7t42m8Ab6sNAUJox34.jpg",
  },
  {
    name: "Prateek Rungta",
    company: "OpenAI",
    company_website: "https://openai.com/",
    title: "Member Technical Staff",
    linkedin: "https://linkedin.com/in/rungtaprateek",
    profile_picture: "https://sessionize.com/image/b42e-400o400o1-Uu23Y4jydHnRuzvS3faACE.jpg",
  },
  {
    name: "Aparna Dhinakaran",
    company: "Arize AI",
    company_website: "https://arize.com/",
    title: "Co-Founder & Chief Product Officer",
    linkedin: "https://www.linkedin.com/in/aparnadhinakaran/",
    profile_picture: "https://sessionize.com/image/23ae-400o400o1-UfWFrGZUdkuEuH5k1PHzoE.jpg",
  },
  {
    name: "Paige Bailey",
    company: "DeepMind",
    company_website: "https://www.deepmind.com",
    title: "Technical Lead",
    linkedin: "https://www.linkedin.com/in/dynamicwebpaige/",
    profile_picture:
      "https://media.licdn.com/dms/image/v2/C5603AQFoBRGAnhVFuQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1516310626986?e=1758758400&v=beta&t=tvXDBMdcN6shvd48skRXJZkNUZJYKv8NJJOtCjgoYxg",
  },
  {
    name: "Yann Leger",
    company: "Koyeb",
    company_website: "https://www.koyeb.com/",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/yannleger/",
    profile_picture:
      "https://media.licdn.com/dms/image/v2/C5603AQGuXA8RXcP8dw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1568807331280?e=1758153600&v=beta&t=pk01dCn8w1e_V-UtXuaw2zOj5HuCco-SU7M2_KtbOIo",
  },
  {
    name: "Robert Brennan",
    company: "OpenHands",
    company_website: "https://www.all-hands.dev",
    title: "CEO of All Hands AI & Co-Creator of OpenHands",
    linkedin: "https://linkedin.com/in/robert-a-brennan",
    profile_picture: "https://sessionize.com/image/62d2-400o400o1-3DaPYZY7SULucDrMfzQzkX.png",
  },
    {
    name: "Daniel Homola",
    company: "BMW Group",
    title: "AI Project Lead",
    linkedin: "https://linkedin.com/in/danielhomola",
    profile_picture: "https://sessionize.com/image/adcf-400o400o1-SRnJoDmtAVm1iHtrZ3Fbw5.jpg",
  },
  {
    name: "Vaibhav Srivastav",
    company: "Hugging Face",
    company_website: "https://huggingface.co/",
    title: "Head of Developer Experience and Community",
    linkedin: "https://www.linkedin.com/in/vaibhavs10/",
    profile_picture: "https://sessionize.com/image/b976-0o0o0-GdYSubDJnET7W9rxkaeEPB.jpg",
  },
  //   {
  //     name: "David Gomes",
  //     company: "Databricks",
  //     company_website: "https://neon.com",
  //     title: "Member of Technical Staff at Neon",
  //     linkedin: "https://www.linkedin.com/in/davidrfgomes/",
  //     profile_picture: "https://sessionize.com/image/6321-400o400o1-WZPkgMtmYBSbfT6CqX9SaY.jpg",
  //   },
  {
    name: "Ivan Burazin",
    company: "Daytona",
    company_website: "https://daytona.io",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/ivanburazin/",
    profile_picture: "https://sessionize.com/image/ba67-400o400o1-RZgw2DqaC7TEEp4b41MiwA.jpg",
  },
  {
    name: "Martin Woodward",
    company: "GitHub",
    company_website: "https://www.github.com",
    title: "Vice President of DevRel",
    linkedin: "https://www.linkedin.com/in/martinwoodward/",
    profile_picture: "https://sessionize.com/image/0b9b-400o400o1-3zvJTMdx1idyBM93y9QUxF.png",
  },
  {
    name: "Oleg	Šelajev",
    company: "Docker",
    company_website: "https://docker.com",
    title: "Testcontainers, AI, & Developer Relations",
    linkedin: "https://www.linkedin.com/in/shelajev/",
    profile_picture: "https://sessionize.com/image/5ca7-400o400o1-nLuHACqrBji1V81wQdQsWE.jpg",
  },
  {
    name: "Tuana Çelik",
    company: "LlamaIndex",
    company_website: "https://www.llamaindex.ai/",
    title: "DevRel & AI Engineer",
    linkedin: "https://www.linkedin.com/in/tuanacelik/",
    profile_picture: "https://sessionize.com/image/4adc-400o400o1-hrr259SGBYg7GmdDcmrWjv.jpg",
  },
  {
    name: "Peter Schuurman",
    company: "Google",
    company_website: "https://www.google.com",
    title: "Software Engineer",
    linkedin: "https://www.linkedin.com/in/pwschuurman/",
    profile_picture: "https://sessionize.com/image/7932-400o400o1-WQi9TDxn2njDXoeiGxMsgY.jpg",
  },
  {
    name: "Ekin	Karabulut",
    company: "Nvidia",
    company_website: "https://www.nvidia.com",
    title: "AI/ML Developer Advocate",
    linkedin: "https://www.linkedin.com/in/ekin-karabulut-40baa2187/tr/?originalSubdomain=de",
    profile_picture: "https://sessionize.com/image/eecf-400o400o1-pZJa7toVkK4Y3yXanEAECR.jpg",
  },
  //   {
  //     name: "Alberto Castelo",
  //     company: "Shopify",
  //     company_website: "https://www.shopify.com",
  //     title: "Staff Machine Learning Engineer",
  //     linkedin: "https://www.linkedin.com/in/alberto-castelo-becerra/",
  //     profile_picture: "https://sessionize.com/image/e013-400o400o1-wBYZYt6bVB8bsfBHg4DeWE.jpg",
  //   },
  //   {
  //     name: "Aleksandar Mitic",
  //     company: "Shopify",
  //     company_website: "https://www.shopify.com",
  //     title: "Senior Software Engineer",
  //     profile_picture: "https://sessionize.com/image/5301-400o400o1-W58JTCwpdooqdCRgv5XpE2.png",
  //   },
  //   {
  //     name: "Jo Kelly-Fenton",
  //     company: "Spotify",
  //     company_website: "https://www.spotify.com",
  //     title: "Software Engineer",
  //     linkedin: "https://www.linkedin.com/in/jo-kelly-fenton-68251ab4/",
  //     profile_picture: "https://sessionize.com/image/fc32-400o400o1-Umgjof5mCKrSaWsMNpTuz5.png",
  //   },

  {
    name: "Marlene Mhangami",
    company: "Microsoft",
    company_website: "https://www.microsoft.com",
    title: "Senior Developer Advocate",
    linkedin: "https://www.linkedin.com/in/marlenemhangami/",
    profile_picture: "https://sessionize.com/image/06f1-400o400o1-NuD8zgwsAzMT2MYadvSCe8.jpg",
  },
  //   {
  //     name: "David Campbell",
  //     company: "Scale AI",
  //     company_website: "https://www.scale.com",
  //     title: "AI Risk Security Platform Lead",
  //     linkedin: "https://www.linkedin.com/in/ddcam/",
  //     profile_picture: "https://sessionize.com/image/616d-400o400o1-aUG5QE8E5NEXRBxrZkqCQM.JPG",
  //   },
  {
    name: "Jesús Espino",
    company: "Gitpod",
    company_website: "https://www.gitpod.io",
    title: "Principal Engineer",
    linkedin: "https://www.linkedin.com/in/jesus-espino/",
    profile_picture: "https://sessionize.com/image/4415-400o400o1-axX3XUeP9guNAQug9iBjgf.jpg",
  },
  {
    name: "Thomas Schmidt",
    company: "Metabase",
    company_website: "https://www.metabase.com",
    title: "AI Engineer",
    linkedin: "https://www.linkedin.com/in/thomas-heinz-schmidt/",
    profile_picture: "https://sessionize.com/image/3ba7-400o400o1-Wd4mFZV9U1ojfdZCLPUEeD.png",
  },

  {
    name: "Tomas Reimers",
    company: "Graphite",
    company_website: "https://www.graphite.dev/",
    title: "Co-Found & Chief Product Officer",
    linkedin: "https://www.linkedin.com/in/tomasreimers/",
    profile_picture: "https://sessionize.com/image/e632-400o400o1-7LznDxW8kd8qGDQVVHE12t.jpg",
  },
  {
    name: "Lars Trieloff",
    company: "Adobe",
    company_website: "https://www.adobe.com",
    title: "Principal",
    linkedin: "https://www.linkedin.com/in/trieloff/?originalSubdomain=de",
    profile_picture: "https://sessionize.com/image/746b-400o400o1-X3k8wYiwiv5f6ytiM4KcZM.png",
  },
  {
    name: "Bertrand	Charpentier",
    company: "Pruna AI",
    company_website: "https://www.pruna.ai/",
    title: "Co-Founder, President, Chief Scientist",
    linkedin: "https://www.linkedin.com/in/bertrand-charpentier-76995ab6/",
    profile_picture: "https://sessionize.com/image/6506-400o400o1-LvxzBU9S96q8xpUogD4WnG.jpg",
  },
  {
    name: "Pierre Burgy",
    company: "Strapi",
    company_website: "https://www.strapi.io",
    title: "Co-Founder & CEO",
    linkedin: "https://www.linkedin.com/in/pierre-burgy-strapi-88671673/",
    profile_picture: "https://sessionize.com/image/69a6-400o400o1-R8YmCmMn14oKvKC58rNqPn.jpg",
  },
  {
    name: "Daniel Homola",
    company: "BMW Group",
    title: "AI Project Lead",
    linkedin: "https://linkedin.com/in/danielhomola",
    profile_picture: "https://sessionize.com/image/adcf-400o400o1-SRnJoDmtAVm1iHtrZ3Fbw5.jpg",
  },
  {
    name: "Anastasia Marchenkova",
    company: "Independant",
    company_website: "https://www.amarchenkova.com",
    title: "Quantum Physicist, Founder, and Tech Influencer",
    linkedin: "https://www.linkedin.com/in/amarchenkova",
    profile_picture: "https://sessionize.com/image/65cd-400o400o1-ntqskth2v4E3Z2EzjCWuJr.jpg",
  },
  {
    name: "Yann Leger",
    company: "Koyeb",
    company_website: "https://www.koyeb.com",
    title: "Co-Founder and CEO",
    linkedin: "https://www.linkedin.com/in/yannleger/",
    profile_picture: "https://sessionize.com/image/bd3a-0o0o0-TmGow4cNSGRc5P3LzYETi3.jpg",
  },
  {
    name: "Jen Person",
    company: "Koyeb",
    company_website: "https://www.koyeb.com",
    title: "Founding Developer Relations Engineer",
    linkedin: "https://www.linkedin.com/in/jennifer-person/",
    profile_picture: "https://sessionize.com/image/fbbc-0o0o0-EuJUadd1HRDYZWW8tpGCTZ.png",
  }
];
